// DOMAIN REPOSITORY ADALAH BUKAN SEMBARANGAN CLASS TAPI ABSTRACT CLASS

// ABSTRACT CLASS ADALAH KELAS YANG HANYA BILANG KITA BISA NGAPAIN SAJA DI CLASS INI
//  DEKLARASIKAN DI CLASS INI BISA APA SAJA.

import 'package:blog_app/core/error/failure.dart';

import '../entities/profile.dart';
import 'package:dartz/dartz.dart';

abstract class ProfileRepository {
  Future<Either<Failure, List<Profile>>> getAllUsers(
    int page,
  ); // EITHER (kiri gagal, kanan berhasil) ? <Failure || List<Profile>>
  Future<Either<Failure, Profile>> getUser(int id);
}

// PADA REPOSITORY KITA AKAN DAPAT 2 KEMUNGKINAN YAITU GAGAL ATAU BERHASIL
// DISINILAH PERAN DARI DARTZ DIMANA KITA MENDAPATKAN HANDLER UNTUK 2 KONDISI TERSEBUT
// ! EITHER ADALAH INISIALISASAI BAHWA SEBUAH FUNCTION ADALAH FUNCTION DARTZ

// !! PENTING
// JIKA FILURE DILETAKKAN DISINI MAKA NANTI DI HALAMAN LAIN AKAN BUAT LAGI DONG OLEH KARENA ITU KITA BUAT
// DIA MENJADI GENERAL DIDALAM FOLDER YANG NAMANYA CORE


// !! SAAT SEMUA REPOSITORY SUDAH IMPLEMENT EITHER MAKA USE CASE AKAN ERROR 
// HAL INI DISEBABKAN KARENA DIA JUGA BUTUH KANAN DAN KIRI JUGA YAITU EITHER